//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Axis2.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_LICENCE1                    102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_LICENCE2                    104
#define IDS_LICENCE3                    105
#define IDS_COPY1                       106
#define IDS_COPY2                       107
#define IDS_COPY3                       108
#define IDS_COPY4                       109
#define IDS_COPY5                       110
#define IDS_COPY6                       111
#define IDS_SETBUTTON                   112
#define IDS_ACCOUNT                     113
#define IDS_TAB                         114
#define IDS_RESETBUTTON                 115
#define IDS_PRIV02                      116
#define IDS_PRIV08                      117
#define IDS_PRIV010                     118
#define IDS_PRIV020                     119
#define IDS_PRIV040                     120
#define IDS_PRIV080                     121
#define IDS_PRIV0200                    122
#define IDS_PRIV0400                    123
#define IDS_PRIV0800                    124
#define IDS_PRIV02000                   125
#define IDS_PRIV04000                   126
#define IDS_RESDISP0                    127
#define IDR_MAINFRAME                   128
#define IDS_RESDISP1                    128
#define IDD_LOG_TAB                     129
#define IDS_RESDISP2                    129
#define IDS_RESDISP3                    130
#define IDD_PROGRESS                    131
#define IDS_RESDISP4                    131
#define IDS_RESDISP5                    132
#define IDD_PROFILE_TAB                 133
#define IDD_PROFILE_DLG                 133
#define IDS_RESDISP6                    133
#define IDD_SPAWN_TAB                   134
#define IDI_FOLDER                      134
#define IDS_RESDISP7                    134
#define IDD_ITEMS_TAB                   135
#define IDI_DOC                         135
#define IDS_PLVL0                       135
#define IDD_LAUNCHER_TAB                136
#define IDS_PLVL1                       136
#define IDS_PLVL2                       137
#define IDD_TRAVEL_TAB                  138
#define IDI_ARROWUP                     138
#define IDS_PLVL3                       138
#define IDD_COMMANDS_TAB                139
#define IDI_ARROWDOWN                   139
#define IDS_PLVL4                       139
#define IDS_PLVL5                       140
#define IDD_ITEMTWEAK_TAB               141
#define IDS_PLVL6                       141
#define IDD_GENERAL_TAB                 142
#define IDS_PLVL7                       142
#define IDS_GPLVL                       143
#define IDD_PLAYERTWEAK_TAB             144
#define IDS_GPRIV                       144
#define IDD_ADD_DESTINATION             145
#define IDS_GRESDISP                    145
#define IDI_SARROWLEFT                  146
#define IDS_NOCATSEL                    146
#define IDS_NOSUBSEL                    147
#define IDI_SARROWRIGHT                 148
#define IDS_NODESC                      148
#define IDI_SARROWUP                    149
#define IDS_ADDDESTINATION              149
#define IDI_SARROWDOWN                  150
#define IDS_INVALCOORD                  150
#define IDI_SARROWDOWNR                 151
#define IDS_INVALMAP                    151
#define IDI_SARROWLEFTD                 152
#define IDS_CATEGORY                    152
#define IDI_SARROWRIGHTU                153
#define IDS_SUBSECTION                  153
#define IDI_SARROWUPL                   154
#define IDS_DESCRIPTION                 154
#define IDS_X                           155
#define IDS_Y                           156
#define IDS_Z                           157
#define IDS_MAP                         158
#define IDS_OK                          159
#define IDS_CANCEL                      160
#define IDS_START                       161
#define IDS_NONE                        162
#define IDS_SHUTDOWN                    163
#define IDI_PALETTE                     164
#define IDS_LOADDEFAULT                 164
#define IDS_LOADREGISTRY                165
#define IDS_AXISTITLE                   166
#define IDI_FIND                        167
#define IDS_SETTINGS                    167
#define IDS_CLIENTINST                  168
#define IDS_ERRNOCLIENT                 169
#define IDS_CLIENTVER                   170
#define IDS_CLIENTPATH                  171
#define IDS_ERRNOMUL                    172
#define IDD_REMOTECONSOLEDLG            174
#define IDB_BITMAP1                     176
#define IDD_DOORWIZARD                  179
#define IDR_MENU1                       180
#define IDD_TOOLBAR                     184
#define IDD_SEARCHCRITDLG               186
#define IDD_COLOR_DLG                   187
#define IDI_COMMANDS                    187
#define IDD_ACCOUNT_TAB                 188
#define IDI_LAUNCHER                    193
#define IDI_ICON2                       194
#define IDI_REMINDER                    196
#define IDI_SETTINGS                    197
#define IDI_WORLD                       198
#define IDI_GENERAL                     199
#define IDI_SPAWN                       200
#define IDI_CHARTWEAK                   201
#define IDI_ITEMTWEAK                   202
#define IDI_ITEMS                       203
#define IDI_LOGS                        204
#define IDI_ACCOUNT                     205
#define IDI_MISC                        206
#define IDR_MENU2                       207
#define IDI_ZOOMOUT                     215
#define IDI_ZOOMIN                      216
#define IDD_REMOTE_CONSOLE_LOGIN_DLG    232
#define IDD_PROFILE_LOGIN_DLG           234
#define IDD_WORLDMAP                    235
#define IDD_LIGHTWIZARD                 236
#define IDD_SETTING_GENERAL             237
#define IDD_SETTING_TRAVEL              238
#define IDD_SETTING_ITEM                239
#define IDD_SETTING_SPAWN               240
#define IDD_SETTING_PATHS               241
#define IDD_REMINDER_TAB                242
#define IDD_REMINDER                    243
#define IDD_SETTING_PATH_OVERRIDE       244
#define IDD_MISC_TAB                    245
#define IDD_SCRIPT_EDITOR               246
#define IDD_SCRIPT_INFO                 247
#define IDD_WORLDMAP1                   248
#define IDD_MULTIVIEW                   248
#define IDC_FINDAREA                    1000
#define IDC_SPREMOVE                    1001
#define IDC_CLIENTBROWSE                1001
#define IDC_SENDTEXT                    1001
#define IDC_ADD                         1001
#define IDC_SPFREEZE                    1002
#define IDC_AS_MULBROWSE                1002
#define IDC_SENDCOMMAND                 1002
#define IDC_EDIT                        1002
#define IDC_SETHEARALL                  1002
#define IDC_FRAMELOG                    1002
#define IDC_RECONNECT                   1003
#define IDC_DELETE                      1003
#define IDC_ITEMCOLOR                   1003
#define IDC_SETALLMOVE                  1003
#define IDC_LOAD                        1004
#define IDC_ITPALETTE                   1004
#define IDC_WORLDMAP                    1004
#define IDC_SAVE                        1005
#define IDC_FIX                         1005
#define IDC_SETDETAIL                   1006
#define IDC_TRACK                       1006
#define IDC_EXPORT                      1007
#define IDC_CLIENTS                     1007
#define IDC_NORTH                       1007
#define IDC_DEFAULTCLIENT               1008
#define IDC_DEFAULTCHECK                1008
#define IDC_REMCONSOLE                  1008
#define IDC_WEST                        1008
#define IDC_DEFUALTMULPATH              1009
#define IDC_DIRBROWSE                   1009
#define IDC_SERVERINFO                  1009
#define IDC_DOORNE                      1009
#define IDC_SAVESCRIPTS                 1010
#define IDC_ITEMINFO                    1010
#define IDC_DOORLIST                    1010
#define IDC_CANCEL                      1011
#define IDC_ADMIN                       1011
#define IDC_VERSION                     1012
#define IDC_LOADRESOURCE                1012
#define IDC_LIGHTLIST                   1012
#define IDC_CURPROFILE                  1013
#define IDC_TELE                        1013
#define IDC_LIGHT1                      1013
#define IDC_WEBPROFILE                  1014
#define IDC_LINK                        1014
#define IDC_LIGHT2                      1014
#define IDC_XSCROLL                     1015
#define IDC_DUPE                        1015
#define IDC_LIGHT3                      1015
#define IDC_YSCROLL                     1016
#define IDC_NUKE                        1016
#define IDC_SCROLLLIGHT                 1016
#define IDC_FRAMETEXT                   1017
#define IDC_SHRINK                      1018
#define IDC_OK                          1018
#define IDC_LIST                        1018
#define IDC_TITLE                       1019
#define IDC_SETDEBUG                    1020
#define IDC_ADDBTN                      1020
#define IDC_WORLDSAVE                   1021
#define IDC_REMOVEBTN                   1021
#define IDC_SLIDER1                     1022
#define IDC_EDITBTN                     1022
#define IDC_SAVESTATICS                 1023
#define IDC_ADDTAB                      1023
#define IDC_RESTOCKALL                  1024
#define IDC_DELTAB                      1024
#define IDC_MONTHLY                     1024
#define IDC_RESYNC                      1025
#define IDC_CLEARTAB                    1025
#define IDC_WEEKLY                      1025
#define IDC_SETLIGHT                    1026
#define IDC_DAILY                       1026
#define IDC_DRY                         1027
#define IDC_TIMEPICKER                  1027
#define IDC_RAIN                        1028
#define IDC_DATEPICKER                  1028
#define IDC_SNOW                        1029
#define IDC_ONCE                        1029
#define IDC_PAGEON                      1030
#define IDC_STARTUP                     1030
#define IDC_LOCATIONS                   1031
#define IDC_CREATURELIST                1031
#define IDC_PROFILES                    1031
#define IDC_PAGEOFF                     1031
#define IDC_NEVER                       1031
#define IDC_PAGEORIGIN                  1032
#define IDC_ENABLE_LOGGING              1033
#define IDC_LOCKITEM                    1033
#define IDC_PAGEPLAYER                  1033
#define IDC_TAB                         1033
#define IDC_WEEKDAY                     1033
#define IDC_PAGEJAIL                    1034
#define IDC_CAPTION                     1034
#define IDC_ADMINISTRATORPRIVS          1034
#define IDC_PAGEKICK                    1035
#define IDC_COMMAND                     1035
#define IDC_OWNERPRIVS                  1035
#define IDC_TEXT                        1035
#define IDC_DRAWDIFS                    1036
#define IDC_PAGEDISCONNECT              1036
#define IDC_TABTEXT                     1036
#define IDC_ALWAYS_ONTOP                1037
#define IDC_STATICNAME                  1037
#define IDC_PAGEQUEUE                   1037
#define IDC_PATHBROWSE                  1037
#define IDC_ROOMVIEW                    1038
#define IDC_STATICDIR                   1038
#define IDC_PAGELIST                    1038
#define IDC_RESETPATH                   1038
#define IDC_DISABLE_TOOLBAR             1038
#define IDC_DRAWSTATICS                 1039
#define IDC_STATICURL                   1039
#define IDC_PAGEDELETE                  1039
#define IDC_PATHLIST                    1039
#define IDC_ROOMVIEW2                   1039
#define IDC_SYSCLOSE                    1040
#define IDC_ARCHCANMOVE                 1040
#define IDC_KILL                        1040
#define IDC_LOADDEFAULT                 1041
#define IDC_BLANK1                      1041
#define IDC_JAIL                        1041
#define IDC_RESDISP5                    1041
#define IDC_LIGHTLEVEL                  1041
#define IDC_SHOWSPWANPOINT              1042
#define IDC_BLANK2                      1042
#define IDC_RESURECT                    1042
#define IDC_LIGHTVALUE                  1042
#define IDC_RESDISP6                    1042
#define IDC_AS_USESAMEPATHASCLIENT      1043
#define IDC_SLEEP                       1043
#define IDC_ITEMBGCOL                   1043
#define IDC_RESDISP7                    1043
#define IDC_ITEMVIEW                    1044
#define IDC_INCOGNITO                   1044
#define IDC_FORGIVE                     1044
#define IDC_NPCVIEW                     1045
#define IDC_SPIRITSPEAK                 1045
#define IDC_DISCONNECT                  1045
#define IDC_ITEMBG_COLOR                1045
#define IDC_MAPVIEW                     1046
#define IDC_INSUBSTANTIAL               1046
#define IDC_STOCK                       1046
#define IDC_TILEDISPLAY                 1046
#define IDC_SPAWNBG_COLOR               1046
#define IDC_HAS_SHIELD                  1047
#define IDC_PURCHASES                   1047
#define IDC_FRAME_SELECT                1047
#define IDC_EMOTE                       1048
#define IDC_BUY                         1048
#define IDC_SCRIPT_PAGE                 1048
#define IDC_COMMCRYSTAL                 1049
#define IDC_GMTOGGLE                    1049
#define IDC_FREEZE                      1050
#define IDC_XRESTOCK                    1050
#define IDC_INFO_SCREEN                 1050
#define IDC_STATICLNAME                 1051
#define IDC_SELL                        1051
#define IDC_HALLUCINATING               1052
#define IDC_STATICLACCT                 1052
#define IDC_SAMPLES                     1052
#define IDC_HIDDEN                      1053
#define IDC_STATICLPASS                 1053
#define IDC_ID_SEARCH                   1053
#define IDC_STATICLIP                   1054
#define IDC_DEF_SEARCH                  1054
#define IDC_RESET_ITEMS                 1054
#define IDC_CRIMINAL                    1055
#define IDC_STATICLPORT                 1055
#define IDC_DESC_SEARCH                 1055
#define IDC_RESET_PATHS                 1055
#define IDC_STATICNPCCOL                1056
#define IDC_CONJURED                    1056
#define IDC_RESET_GENERAL               1056
#define IDC_STATICITEMCOL               1057
#define IDC_MOUNTED                     1057
#define IDC_RESET_OVERPATHS             1057
#define IDC_SEARCH_ID                   1058
#define IDC_STATICFREEZE                1058
#define IDC_GUESTPRIVS                  1058
#define IDC_RESET_SPAWN                 1058
#define IDC_MAPPLANE                    1059
#define IDC_HOMEDIST                    1059
#define IDC_ACCT                        1059
#define IDC_NAME                        1059
#define IDC_LOGFRAME                    1059
#define IDC_ITEMMISC                    1059
#define IDC_NUDGEAMOUNT                 1059
#define IDC_ARTINDEX                    1059
#define IDC_PLAYERPRIVS                 1059
#define IDC_LICENSE                     1059
#define IDC_RESET_TRAVEL                1059
#define IDC_MIN_TIME                    1060
#define IDC_SEARCH_DESCRIPTION          1060
#define IDC_CONSOLE_SEND                1060
#define IDC_BASEDIR                     1060
#define IDC_ITEMTAG                     1060
#define IDC_NUKEARG                     1060
#define IDC_COUNSELORPRIVS              1060
#define IDC_SPAWNBGCOL                  1060
#define IDC_COPYRIGHT                   1060
#define IDC_MAX_TIME                    1061
#define IDC_SEARCH_VALUE                1061
#define IDC_COMMAND_SEND                1061
#define IDC_ACCTNAME                    1061
#define IDC_URL                         1061
#define IDC_TYPES                       1061
#define IDC_TYPELIST                    1061
#define IDC_SEERPRIVS                   1061
#define IDC_MULTIVIEW                   1061
#define IDC_MAX_DIST                    1062
#define IDC_ADDRESS                     1062
#define IDC_ITEMMISCVALUE               1062
#define IDC_HUELIST                     1062
#define IDC_GMPRIVS                     1062
#define IDC_SPELL_LIST                  1062
#define IDC_PASSWORD                    1063
#define IDC_ITEMTAGVALUE                1063
#define IDC_DEVELOPERPRIVS              1063
#define IDC_SOUND_LIST                  1063
#define IDC_PREFIX                      1063
#define IDC_INDOORS                     1064
#define IDC_ALTCLIENT                   1064
#define IDC_ITEMSETMISC                 1064
#define IDC_SLIDERVALUE                 1064
#define IDC_MUSIC_LIST                  1064
#define IDC_PREFIX2                     1064
#define IDC_UOTITLE                     1064
#define IDC_SAVEPARITY                  1065
#define IDC_ITEMSETTAG                  1065
#define IDC_PWD                         1066
#define IDC_BRAIN                       1066
#define IDC_SKILL                       1067
#define IDC_GPLVL                       1067
#define IDC_SKILLVALUE                  1068
#define IDC_GPRIV                       1068
#define IDC_RESISTENCE                  1069
#define IDC_GRESDISP                    1069
#define IDC_STATS                       1070
#define IDC_CAT                         1070
#define IDC_STATVALUE                   1071
#define IDC_RESDISP0                    1071
#define IDC_SUB                         1071
#define IDC_STARTTAB                    1072
#define IDC_FLAG_VALUE                  1072
#define IDC_RESDISP1                    1072
#define IDC_DESC                        1072
#define IDC_INVULNERABLE                1073
#define IDC_RESDISP2                    1073
#define IDC_X                           1073
#define IDC_LANGUAGE                    1073
#define IDC_DEAD                        1074
#define IDC_RESDISP3                    1074
#define IDC_Y                           1074
#define IDC_RESISTENCEVALUE             1075
#define IDC_RESDISP4                    1075
#define IDC_Z                           1075
#define IDC_INVISIBLE                   1076
#define IDC_SETPRIVS                    1076
#define IDC_MAP                         1076
#define IDC_EVENTS                      1077
#define IDC_RESET_PRIVS                 1077
#define IDC_GP_INFO                     1077
#define IDC_WARMODE                     1078
#define IDC_PRIV02                      1078
#define IDC_GP_MISC                     1078
#define IDC_REACTIVE_ARMOR              1079
#define IDC_PRIV08                      1079
#define IDC_GP_VENDORS                  1079
#define IDC_POISONED                    1080
#define IDC_PRIV010                     1080
#define IDC_GP_WEATHER                  1080
#define IDC_NIGHTSIGHT                  1081
#define IDC_PRIV020                     1081
#define IDC_MAGIC_REFLECT               1082
#define IDC_PRIV040                     1082
#define IDC_SELF                        1082
#define IDC_POLYMORPHED                 1083
#define IDC_PRIV080                     1083
#define IDC_GP_DISCIPLINE               1083
#define IDC_STONE                       1084
#define IDC_PRIV0200                    1084
#define IDC_GP_GMPAGE                   1084
#define IDC_FLYING                      1085
#define IDC_PRIV0400                    1085
#define IDC_PRIV0800                    1086
#define IDC_TOOLGENERAL                 1086
#define IDC_PET                         1087
#define IDC_PRIV02000                   1087
#define IDC_TOOLNPCTWEAK                1087
#define IDC_SPAWNED                     1088
#define IDC_PRIV04000                   1088
#define IDC_TOOLTRAVEL                  1088
#define IDC_INTERNALNAME                1088
#define IDC_MISC                        1089
#define IDC_PRIVVALUE                   1089
#define IDC_TOOLSPAWN                   1089
#define IDC_COLINDEX                    1089
#define IDC_FINDNPC                     1090
#define IDC_MISCVALUE                   1090
#define IDC_TOOLITEMS                   1090
#define IDC_BRIGHT                      1090
#define IDC_RIDDEN                      1091
#define IDC_TOOLMISC                    1091
#define IDC_DARK                        1091
#define IDC_RESETFLAGS                  1092
#define IDC_TOOLITEMTWEAK               1092
#define IDC_TYPE                        1092
#define IDC_SETFLAGS                    1093
#define IDC_TOOLACCOUNT                 1093
#define IDC_INDEX                       1093
#define IDC_TAG                         1094
#define IDC_TAGVALUE                    1095
#define IDC_IDENTIFIED                  1096
#define IDC_DECAY                       1097
#define IDC_NEWBIE                      1098
#define IDC_TOOLLAUNCHER                1098
#define IDC_ALWAYSMOVEABLE              1099
#define IDC_NEVERMOVEABLE               1100
#define IDC_TOOLCOMMANDS                1100
#define IDC_MAGIC                       1101
#define IDC_TOOLREMINDER                1101
#define IDC_OWNEDBYTOWN                 1102
#define IDC_TOOLLOGS                    1102
#define IDC_RESET_ATTR                  1103
#define IDC_TOOLSETTINGS                1103
#define IDC_SETATTR                     1104
#define IDC_ATTRVALUE                   1105
#define IDC_SETTYPES                    1106
#define IDC_OPENDOORWIZ                 1107
#define IDC_OPENLIGHTWIZ                1108
#define IDC_SPELL_ID                    1109
#define IDC_CURSED                      1110
#define IDC_CAST_SPELL                  1110
#define IDC_DAMNED                      1111
#define IDC_BLESSED                     1112
#define IDC_SACRED                      1113
#define IDC_FORSALE                     1114
#define IDC_STOLEN                      1115
#define IDC_CANDECAY                    1116
#define IDC_SETPRIV                     1117
#define IDC_SETRESDISP                  1119
#define IDC_CLOSE                       1123
#define IDC_RESETSTING                  1124
#define IDC_GO                          1126
#define IDC_SEND                        1127
#define IDC_WHERE                       1128
#define IDC_ADDLOC                      1131
#define IDC_REMLOC                      1132
#define IDC_EDITLOC                     1133
#define IDC_LOCATE                      1134
#define IDC_CREATE                      1139
#define IDC_FLIP                        1140
#define IDC_REMOVE                      1141
#define IDC_TILE                        1142
#define IDC_ZTILE                       1143
#define IDC_AMOUNT                      1144
#define IDC_MAXDIST                     1145
#define IDC_MINTIME                     1146
#define IDC_MAXTIME                     1147
#define IDC_PLACESPAWN                  1148
#define IDC_INITSPAWN                   1149
#define IDC_ITEMID                      1151
#define IDC_SPAWNRATE                   1152
#define IDC_LAUNCH3D                    1153
#define IDC_ITEMIDDEC                   1153
#define IDC_NEW                         1154
#define IDC_LAUNCHAUTO                  1155
#define IDC_LAUNCH2D                    1156
#define IDC_DONE                        1157
#define IDC_LAUNCHALT                   1158
#define IDC_IPADDRESS                   1159
#define IDC_ACCOUNT                     1160
#define IDC_PORT                        1161
#define IDC_ACCOUNT_LIST                1162
#define IDC_EDITACCT                    1163
#define IDC_STATUS_MESSAGE              1166
#define IDC_XCOORD                      1167
#define IDC_YCOORD                      1168
#define IDC_ZCOORD                      1169
#define IDC_PLANE                       1170
#define IDC_CATEGORY                    1171
#define IDC_SUBSECTION                  1172
#define IDC_DESCRIPTION                 1173
#define IDC_NPC_ID                      1177
#define IDC_SUMMON                      1178
#define IDC_PLACE_SPAWNPOINT            1179
#define IDC_INIT_SPAWNPOINT             1180
#define IDC_SETHOME                     1181
#define IDC_SETHOMEDIST                 1182
#define IDC_NPC_IDDEC                   1183
#define IDC_CATEGORYTREE                1184
#define IDC_NPCTREE                     1185
#define IDC_CATEGORY_TREE               1186
#define IDC_ITEMS                       1187
#define IDC_COORDS                      1227
#define IDC_MUSIC_ID                    1231
#define IDC_PLAYMIDI                    1232
#define IDC_STOPMIDI                    1233
#define IDC_SFX_ID                      1234
#define IDC_PLAY_SFX                    1235
#define IDC_NUDGEUP                     1236
#define IDC_SEND_SFX                    1236
#define IDC_NUDGEDOWN                   1237
#define IDC_STOP_SFX                    1237
#define IDC_MOVE8                       1238
#define IDC_SENDMIDI                    1238
#define IDC_SETBRAIN                    1240
#define IDC_SETEDIT                     1240
#define IDC_SETSKILL                    1241
#define IDC_MOVE2                       1241
#define IDC_SETSTAT                     1242
#define IDC_SETEVENTS                   1242
#define IDC_MOVE1                       1242
#define IDC_SETRESISTENCE               1243
#define IDC_DELEVENTS                   1243
#define IDC_MOVE7                       1243
#define IDC_ADDEVENT                    1244
#define IDC_MOVE6                       1244
#define IDC_SETMISC                     1245
#define IDC_MOVE3                       1245
#define IDC_SETTAG                      1246
#define IDC_MOVE5                       1246
#define IDC_REMOVEEVENT                 1247
#define IDC_MOVE4                       1247
#define IDC_ABOUTTITLE                  1249
#define IDC_ABOUTTIMESTAMP              1250
#define IDC_ABOUTTITLE2                 1251
#define IDC_ABOUTCOPYNEW                1251
#define IDC_SERVER_VERSION              1253
#define IDC_NPC_COLOR                   1282
#define IDC_ITEM_COLOR                  1283
#define IDC_PALETTE                     1304
#define IDC_SPECTRUM                    1305
#define IDC_SHADESLIDER                 1306
#define IDC_COLORINDEX                  1307
#define IDC_MOVINGCOLOR                 1309
#define IDC_HUENAME                     1310
#define IDC_ITSPECTRUM                  1311
#define IDC_QUICKPICK                   1312
#define IDC_PROGBAR                     1362
#define IDC_RE_CONSOLE                  1364
#define IDC_ZOOMOUT                     1379
#define IDC_ZOOMIN                      1380
#define IDC_FINDITEM                    1381
#define IDC_TRAVELMAP                   1382
#define IDC_WORLD                       1383
#define IDC_DISPLAY                     1385
#define IDC_NPCDISPLAY                  1386
#define IDC_DOORNW                      1386
#define IDC_DOORSE                      1387
#define IDC_DOORSW                      1388
#define IDC_COLORPREVIEW                1392
#define IDC_AVAILABLESCRIPTS            1398
#define IDC_ALLOWMULTIPLE               1399
#define ID_HELP_ABOUTAXIS2              32771
#define ID_HELP_DOCUMENTATION           32772
#define ID_SETTINGS_BASIC               32773
#define ID_SETTINGS_ITEMTAB             32774
#define ID_SETTINGS_TRAVELTAB           32775
#define ID_SETTINGS_SPAWNTAB            32776
#define ID_SETTINGS_GENERAL             32777
#define ID_EXIT_CLOSEAXIS2              32778
#define ID_SETTINGS_FILEPATHS           32779
#define ID_SETTINGS_OVERRIDEMULPATHS    32780
#define ID_SETTINGS_OVERRIDEPATHS       32781
#define ID_PROFILES_OPTION              32782
#define ID_PROFILES_UNLOAD              32783
#define ID_PROFILES_LOADDEFAULT         32784
#define ID_PROFILES_LOADLASTPROFILE     32785
#define ID_MULTESTINGMENU_READANIM      32786
#define ID_TOOLBARMENU_SETTINGS         32788
#define ID_TOOLBARMENU_PROFILE          32789
#define ID_TOOLBARMENU_HELP             32790
#define ID_TOOLBARMENU_EXIT             32791
#define IDC_STATICS                     -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
